name: generate animation

on: push

jobs:
  snake-animation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: cjjcastro
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
    
  metrics-github:
    runs-on: ubuntu-latest
    steps:
      - name: Github metrics
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
